Repository AY2223S2-CS2103-F11-4/tp, pull requests merged in 2023-03, with the labels that each got.

#28 V1.2 [Sheng han]
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PersonalPane.java
  src/main/resources/images/spongbob.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PersonalPane.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#31 V1.2 [Add in individual pane]
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PersonalPane.java
Labels: priority.High, type.Task

#32 V1.2 [Changes in person card class to fix image implementation]
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, type.Task, severity.Medium

#33 v1.2 [Fix bug for disappearing personal pane upon scrolling]
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PersonalPane.java
  src/main/resources/view/PersonalPane.fxml
Labels: type.Bug, severity.VeryLow

#47 V1.2b [Add status variable in Person class]
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddImageCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ChsContacts.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/SocContacts.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonalPane.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonalPane.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Task

#49 [v1.2b] Expand tag pane in personal pane
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/AccommodationTag.java
  src/main/java/seedu/address/model/tag/AffiliationTag.java
  src/main/java/seedu/address/model/tag/CommitmentTag.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonalPane.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#67 V1.3 [Update DG]
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.High, type.Task

#68 V1.3 [Add tag colours to labels]
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/CommitmentTag.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonalPane.java
  src/main/resources/view/Style.css
Labels: priority.Medium, type.Task

#71 V1.3 [Bug fixes in personal pane + modify tag in edit parser]
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/tag/AffiliationTag.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonalPane.java
  src/main/resources/view/PersonalPane.fxml
  src/main/resources/view/Style.css
Labels: type.Bug, priority.High, type.Task, severity.High

#72 Fix UG command summary for find command
  docs/UserGuide.md
Labels: documentation

#82 [v1.3] Set character limits to input variables
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Status.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Bug
